version: '3'

networks:
  app:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql
    networks:
      - app

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: user_wallet
      MYSQL_USER: user_wallet
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - app

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./www:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./www/app:/var/www/html/app
    working_dir: /var/www/html/app
    command: composer install
    depends_on:
      - php
    networks:
      - app

  npm:
    image: node:latest
    container_name: npm
    volumes:
      - ./www/app:/var/www/html/app
    working_dir: /var/www/html/app
    command: npm install
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./www/app:/var/www/html/app
    depends_on:
      - mysql
    working_dir: /var/www/html/app
    entrypoint: ['php', '/var/www/html/app/artisan']
    networks:
      - app